# base directories
# ==============================
# NOTE: these are all relative to the location of the config file!
# where the script will look for markdown files
content: &CONTENT_DIR "./content/"
# where HTML files will be generated
public: &PUBLIC_DIR "./../docs/"
# referenced only in this yaml file, for now
resources: &RESOURCES_DIR !join [*CONTENT_DIR, "resources/"]

# pandoc stuff
# ==============================
# these files will be passed as arguments to pandoc
# `!join` is a custom directive that will add the elements of the list together. 
# useful for concatenating strings
header: !join [*RESOURCES_DIR, "header.html"] # passed as '--include-in-header'
before: !join [*RESOURCES_DIR, "before-body.html"] # passed as '--include-before-body'
after: !join [*RESOURCES_DIR, "after-body.html"] # passed as '--include-after-body'

# these should be paths to any pandoc filters you'd like to use. 
# if you dont have any, just have it be an empty list
filters: [] 

# other things
# ==============================
make_index_files: true # whether to treat files with `index: true` specially
generated_index_suffix: "._index.md" # dont worry about this, its for generating temporary files

# whether to give each HTML file a final pass with the mustache renderer, 
# with the frontmatter from the markdown source passed as the context
mustache_rerender: true 